In [1]:
import pandas as pd
import numpy as np
df= pd.read_csv('movie_reviews.csv')
df.head(10)

Summary  Sentiment
0  rock destined st century new conan going make ...          1
1  gorgeously elaborate continuation lord ring tr...          1
2                             effective tepid biopic          1
3  sometimes like go movie fun wasabi good place ...          1
4  emerges something rare issue movie honest keen...          1
5  film provides great insight neurotic mindset c...          1
6     offer rare combination entertainment education          1
7  perhaps picture ever made literally showed roa...          1
8  steer turn snappy screenplay curl edge clever ...          1
9  take care cat offer refreshingly different sli...          1

In [3]:
summary = df.Summary.values
labels = df.Sentiment.values

In [4]:
print(summary)

['rock destined st century new conan going make splash even greater arnold schwarzenegger jean claud van damme steven segal'
 'gorgeously elaborate continuation lord ring trilogy huge column word cannot adequately describe co writer director peter jackson expanded vision j r r tolkien middle earth'
 'effective tepid biopic' ...
 'stand crocodile hunter hurried badly cobbled look godzilla combined scene japanese monster flick canned shot raymond burr commenting monster path destruction'
 'thing look like made home video quickie' 'enigma well made dry placid']


In [5]:
print(labels)

[1 1 1 ... 0 0 0]


In [6]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# tokenizer with a maximum vocabulary size of 1000
tokenizer = Tokenizer(num_words=1000)

# Fit the tokenizer on the text data
tokenizer.fit_on_texts(summary)

# Convert text data to sequences of integers
encoded_docs = tokenizer.texts_to_sequences(summary)

print(encoded_docs)


[[420, 648, 37, 153, 6, 12, 824], [770, 943, 349, 771, 559, 138, 15, 944, 772, 542, 368], [602], [173, 4, 48, 2, 61, 9, 161, 232], [40, 311, 429, 2, 430, 21, 4, 3], [1, 625, 63, 385, 197, 12, 431, 299], [133, 311, 171], [543, 64, 68, 34, 522, 677, 9], [134, 226, 603, 204, 121, 773, 897, 649], [35, 187, 133, 994, 412, 995, 152], [1, 14, 135, 413, 996, 300], [43, 270, 202, 774, 432, 579], [48, 152, 203, 83, 205], [3, 95, 447, 271, 2, 68], [122, 272, 124, 5, 11], [650, 146, 68, 36, 369], [91], [678, 493, 30, 169], [2, 604, 350], [133, 290, 523, 183], [524, 679, 1], [69, 431, 65, 560, 1, 626, 997, 25, 266, 48, 18], [857, 151], [312, 580, 475, 945], [651, 112, 9, 998], [392, 775, 71, 776, 602], [420], [28, 5, 652, 30, 52, 118, 312], [46, 946, 627, 237, 5, 628, 108, 460, 432, 86, 84, 14, 399, 194], [351, 291, 352, 113, 605, 73, 109], [606, 154, 68], [1, 680, 103, 858, 146], [273, 561, 777], [13, 109, 859, 132, 332, 4, 629], [32, 301, 59, 707, 37, 195, 45, 732, 87, 524, 1, 995, 653], [66, 21

In [7]:
# Determine the vocabulary size
vocab_size = len(tokenizer.word_index) + 1  # Adding 1 to account for the reserved 0 index
print(vocab_size)

# Pad sequences to a fixed length of 200
padded_sequence = pad_sequences(encoded_docs, maxlen=200)

16320


In [8]:
print(padded_sequence)

[[  0   0   0 ...   6  12 824]
 [  0   0   0 ... 772 542 368]
 [  0   0   0 ...   0   0 602]
 ...
 [  0   0   0 ... 143 213 498]
 [  0   0   0 ...  34 227 164]
 [  0   0   0 ...  14  34 837]]


In [9]:
(tokenizer.word_index)

{'film': 1,
 'movie': 2,
 'one': 3,
 'like': 4,
 'story': 5,
 'make': 6,
 'character': 7,
 'time': 8,
 'good': 9,
 'comedy': 10,
 'much': 11,
 'even': 12,
 'way': 13,
 'well': 14,
 'director': 15,
 'work': 16,
 'performance': 17,
 'life': 18,
 'little': 19,
 'funny': 20,
 'feel': 21,
 'get': 22,
 'enough': 23,
 'never': 24,
 'u': 25,
 'bad': 26,
 'may': 27,
 'love': 28,
 'best': 29,
 'year': 30,
 'thing': 31,
 'would': 32,
 'look': 33,
 'made': 34,
 'take': 35,
 'come': 36,
 'new': 37,
 'drama': 38,
 'action': 39,
 'something': 40,
 'could': 41,
 'audience': 42,
 'really': 43,
 'see': 44,
 'two': 45,
 'minute': 46,
 'plot': 47,
 'go': 48,
 'long': 49,
 'still': 50,
 'many': 51,
 'old': 52,
 'every': 53,
 'people': 54,
 'big': 55,
 'nothing': 56,
 'first': 57,
 'better': 58,
 'give': 59,
 'end': 60,
 'fun': 61,
 'without': 62,
 'great': 63,
 'picture': 64,
 'actor': 65,
 'though': 66,
 'might': 67,
 'ever': 68,
 'cast': 69,
 'world': 70,
 'also': 71,
 'le': 72,
 'real': 73,
 'kind': 74,

In [12]:
print(summary[0])
print(encoded_docs[0])

rock destined st century new conan going make splash even greater arnold schwarzenegger jean claud van damme steven segal
[420, 648, 37, 153, 6, 12, 824]


In [11]:
print(padded_sequence[0])

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0 420 648  37 153   6
  12 824]


Embedding Layer --->
Recurrent Layer --->
Dense Layer

In [13]:
# Build the  RNN model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Dropout, Embedding, SpatialDropout1D

embedding_vector_length = 32

model_1 = Sequential()
model_1.add(Embedding(vocab_size, embedding_vector_length, input_length=200))
model_1.add(SpatialDropout1D(0.25))  # prevent overfitting in neural networks.
model_1.add(SimpleRNN(50))
# model.add(Dropout(0.2))  # You can uncomment this line if needed
model_1.add(Dense(1, activation='sigmoid'))

model_1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model_1.summary())




Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 200, 32)           522240    
                                                                 
 spatial_dropout1d (Spatial  (None, 200, 32)           0         
 Dropout1D)                                                      
                                                                 
 simple_rnn (SimpleRNN)      (None, 50)                4150      
                                                                 
 dense (Dense)               (None, 1)                 51        
                                                                 
Total params: 526441 (2.01 MB)
Trainable params: 526441 (2.01 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [14]:
history = model_1.fit(padded_sequence,labels,validation_split=0.2, epochs=5, batch_size=32)

Epoch 1/5


267/267 [==============================] - 10s 33ms/step - loss: 0.6446 - accuracy: 0.6324 - val_loss: 1.0678 - val_accuracy: 0.1130
Epoch 2/5
267/267 [==============================] - 10s 36ms/step - loss: 0.5255 - accuracy: 0.7363 - val_loss: 0.8317 - val_accuracy: 0.4810
Epoch 3/5
267/267 [==============================] - 10s 37ms/step - loss: 0.4509 - accuracy: 0.7873 - val_loss: 0.8537 - val_accuracy: 0.5565
Epoch 4/5
267/267 [==============================] - 10s 37ms/step - loss: 0.4325 - accuracy: 0.8020 - val_loss: 2.4238 - val_accuracy: 0.0127
Epoch 5/5
267/267 [==============================] - 10s 37ms/step - loss: 0.4697 - accuracy: 0.7754 - val_loss: 0.8429 - val_accuracy: 0.5612


In [16]:
test_word ="This is very bad"
tw = tokenizer.texts_to_sequences([test_word])
tw = pad_sequences(tw,maxlen=200)
predictions = model_1.predict(np.array(tw))
print(predictions)

1/1 [==============================] - 0s 248ms/step
[[0.14523081]]


In [17]:
# Build the model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense, Dropout
from tensorflow.keras.layers import SpatialDropout1D
from tensorflow.keras.layers import Embedding
embedding_vector_length = 32
model = Sequential()
model.add(Embedding(vocab_size, embedding_vector_length,
                                     input_length=200) )
# model.add(SpatialDropout1D(0.25)) # prevent overfitting in neural networks.
model.add(LSTM(50))
# model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',
                           metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 200, 32)           522240    
                                                                 
 lstm (LSTM)                 (None, 50)                16600     
                                                                 
 dense_1 (Dense)             (None, 1)                 51        
                                                                 
Total params: 538891 (2.06 MB)
Trainable params: 538891 (2.06 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [18]:
history = model.fit(padded_sequence,labels,validation_split=0.2, epochs=5, batch_size=32)

Epoch 1/5
267/267 [==============================] - 17s 56ms/step - loss: 0.6055 - accuracy: 0.6683 - val_loss: 1.0328 - val_accuracy: 0.3633
Epoch 2/5
267/267 [==============================] - 15s 55ms/step - loss: 0.5043 - accuracy: 0.7514 - val_loss: 0.7713 - val_accuracy: 0.5987
Epoch 3/5
267/267 [==============================] - 15s 57ms/step - loss: 0.4776 - accuracy: 0.7691 - val_loss: 0.7424 - val_accuracy: 0.6024
Epoch 4/5
267/267 [==============================] - 15s 58ms/step - loss: 0.4729 - accuracy: 0.7697 - val_loss: 0.8538 - val_accuracy: 0.5462
Epoch 5/5
267/267 [==============================] - 20s 73ms/step - loss: 0.4622 - accuracy: 0.7721 - val_loss: 0.8302 - val_accuracy: 0.5902


In [19]:
test_word ="This is very bad"
tw = tokenizer.texts_to_sequences([test_word])
tw = pad_sequences(tw,maxlen=200)
predictions = model.predict(np.array(tw))
print(predictions)

1/1 [==============================] - 1s 555ms/step
[[0.17531447]]


In [20]:
# Build the model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Dropout, Embedding, SpatialDropout1D

embedding_vector_length = 32

model_2 = Sequential()
model_2.add(Embedding(vocab_size, embedding_vector_length, input_length=200))
model_2.add(SpatialDropout1D(0.25))  # prevent overfitting in neural networks.
model_2.add(GRU(50))
# model_2.add(Dropout(0.2))  # You can uncomment this line if needed
model_2.add(Dense(1, activation='sigmoid'))

model_2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model_2.summary())



Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 200, 32)           522240    
                                                                 
 spatial_dropout1d_1 (Spati  (None, 200, 32)           0         
 alDropout1D)                                                    
                                                                 
 gru (GRU)                   (None, 50)                12600     
                                                                 
 dense_2 (Dense)             (None, 1)                 51        
                                                                 
Total params: 534891 (2.04 MB)
Trainable params: 534891 (2.04 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [21]:
history = model_2.fit(padded_sequence,labels,validation_split=0.2, epochs=5, batch_size=32)

Epoch 1/5
267/267 [==============================] - 23s 78ms/step - loss: 0.6166 - accuracy: 0.6578 - val_loss: 0.7672 - val_accuracy: 0.5654
Epoch 2/5
267/267 [==============================] - 20s 77ms/step - loss: 0.5064 - accuracy: 0.7464 - val_loss: 0.8285 - val_accuracy: 0.4857
Epoch 3/5
267/267 [==============================] - 23s 85ms/step - loss: 0.4796 - accuracy: 0.7660 - val_loss: 0.7279 - val_accuracy: 0.6043
Epoch 4/5
267/267 [==============================] - 28s 105ms/step - loss: 0.4619 - accuracy: 0.7725 - val_loss: 0.7094 - val_accuracy: 0.6362
Epoch 5/5
267/267 [==============================] - 26s 98ms/step - loss: 0.4487 - accuracy: 0.7831 - val_loss: 0.7901 - val_accuracy: 0.6109


In [22]:
test_word ="This is very bad"
tw = tokenizer.texts_to_sequences([test_word])
tw = pad_sequences(tw,maxlen=200)
predictions = model_2.predict(np.array(tw))
print(predictions)

1/1 [==============================] - 0s 463ms/step
[[0.16394737]]


In [23]:
model_2.save("my_model.h5")

C:\Users\shail\anaconda3\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [24]:
model_2.save_weights("my_weights")

In [26]:
import pickle
with open('tokenizer.pkl', 'wb') as f:  # open a text file
    pickle.dump(tokenizer, f) # serialize the list